CREATE TABLE banco (
    id            NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_cotizacion NUMBER NOT NULL,
    nombre        VARCHAR2(50) NOT NULL
);

CREATE TABLE provincia (
    id     NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(50) NOT NULL,
    PRIMARY KEY ( id )
);

CREATE TABLE marca (
    id     NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(50) NOT NULL,
    PRIMARY KEY ( id )
);

CREATE TABLE usuario (
    id               NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre           VARCHAR2(60) NOT NULL,
    primer_apellido  VARCHAR2(60) NOT NULL,
    segundo_apellido VARCHAR2(60) NOT NULL,
    email            VARCHAR2(60) NOT NULL,
    telefono         VARCHAR2(60) NOT NULL,
    password         VARCHAR2(255) NOT NULL,
    permissions      VARCHAR2(45) NOT NULL,
    roles            VARCHAR2(45) NOT NULL,
    active           NUMBER NOT NULL,
    PRIMARY KEY ( id )
);

CREATE TABLE facturapago (
    id         NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_banco   NUMBER NOT NULL,
    id_usuario NUMBER NOT NULL,
    fecha      TIMESTAMP DEFAULT current_timestamp,
    codigo     NUMBER NOT NULL,
    nombre     VARCHAR2(25) NOT NULL,
    email      VARCHAR2(25) NOT NULL,
    PRIMARY KEY ( id )
);

CREATE TABLE estado_vehiculo (
    id     NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(50) NOT NULL,
    PRIMARY KEY ( id )
);

CREATE TABLE carro (
    id           NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario   NUMBER NOT NULL,
    id_marca     NUMBER NOT NULL,
    id_provincia NUMBER NOT NULL,
    id_estado    NUMBER NOT NULL,
    modelo       VARCHAR2(60) NOT NULL,
    transmision  VARCHAR2(60) NOT NULL,
    tipo         VARCHAR2(60) NOT NULL,
    color        VARCHAR2(60) NOT NULL,
    motor        VARCHAR2(60) NOT NULL,
    precio       VARCHAR2(60) NOT NULL,
    direccion    VARCHAR2(200) NOT NULL,
    ruta_imagen  VARCHAR2(200) NOT NULL,
    PRIMARY KEY ( id )
);

CREATE TABLE cotizacion (
    id         NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario NUMBER NOT NULL,
    id_carro   NUMBER NOT NULL,
    fecha      DATE NOT NULL,
    PRIMARY KEY ( id )
);

ALTER TABLE cotizacion
    ADD CONSTRAINT fk_cotizacion_usuario FOREIGN KEY ( id_usuario )
        REFERENCES usuario ( id );

ALTER TABLE cotizacion
    ADD CONSTRAINT fk_cotizacion_carro FOREIGN KEY ( id_carro )
        REFERENCES carro ( id );

ALTER TABLE carro
    ADD CONSTRAINT fk_carros_usuario FOREIGN KEY ( id_usuario )
        REFERENCES usuario ( id );

ALTER TABLE carro
    ADD CONSTRAINT fk_carros_marcas FOREIGN KEY ( id_marca )
        REFERENCES marca ( id );

ALTER TABLE carro
    ADD CONSTRAINT fk_carros_provincia FOREIGN KEY ( id_provincia )
        REFERENCES provincia ( id );

ALTER TABLE carro
    ADD CONSTRAINT fk_carros_estado FOREIGN KEY ( id_estado )
        REFERENCES estado_vehiculo ( id );

ALTER TABLE facturapago
    ADD CONSTRAINT fk_facturapago_banco FOREIGN KEY ( id_banco )
        REFERENCES banco ( id );

ALTER TABLE facturapago
    ADD CONSTRAINT fk_facturapago_usuario FOREIGN KEY ( id_usuario )
        REFERENCES usuario ( id );

ALTER TABLE banco
    ADD CONSTRAINT fk_banco_cotizacion FOREIGN KEY ( id_cotizacion )
        REFERENCES cotizacion ( id );

--CREATE USER TALLERMECANICO IDENTIFIED BY Taller123;
--GRANT SYSDBA TO TALLERMECANICO CONTAINER=ALL;
--GRANT ALL PRIVILEGES TO TALLERMECANICO;
--GRANT CREATE SESSION TO TALLERMECANICO;

COMMIT;