INSERT ALL
    INTO T_MARCA(marca) VALUES ('BMW')
SELECT 1 FROM DUAL;
/
SELECT * FROM T_MARCA;

CREATE OR REPLACE PROCEDURE sp_update_carro (
    V_ID NUMBER,
    V_MARCA NUMBER,
    V_MODELO NUMBER,
    V_KILOMETRAJE NUMBER,
    V_PRECIO	NUMBER,
    V_ESTADO NUMBER
) AS
BEGIN 
    UPDATE T_CARRO SET
        MARCA_ID = V_MARCA,
        MODELO_ID = V_MODELO,
        KILOMETRAJE = V_KILOMETRAJE,
        PRECIO = V_PRECIO,
        ESTADO_ID=V_ESTADO
    WHERE
        CARRO_ID = V_ID;
        
END;
/

CALL SP_UPDATE_CARRO(1,1,1,53810,5000000,1);



CREATE OR REPLACE PROCEDURE sp_delete_carro (
    V_ID NUMBER
) AS
BEGIN 
    DELETE FROM T_CARRO
    WHERE
        carro_id = V_ID;
        
END;

CALL SP_DELETE_CARRO

INSERT INTO T_CARRO(placa,marca_id,modelo_id,)