INSERT ALL
    INTO T_MARCA(marca) VALUES ('BMW')
SELECT 1 FROM DUAL;
/
SELECT * FROM T_MARCA;

CREATE OR REPLACE PROCEDURE sp_crear_carro (
    V_ID NUMBER,
    V_PLACA VARCHAR2,
    V_MARCA NUMBER,
    V_MODELO NUMBER,
    V_TRIM NUMBER,
    V_COLOR_INTERIOR NUMBER,
    V_COLOR_EXTERIOR NUMBER,
    V_SUCURSAL NUMBER,
    V_ESTADO NUMBER,
    V_KILOMETRAJE NUMBER,
    V_PRECIO	NUMBER,
    V_VIN VARCHAR2
) AS
BEGIN 
    INSERT INTO 
        T_CARRO (
          PLACA,
        MARCA_ID,
        MODELO_ID,
        TRIM_ID ,
        COLOR_INTERIOR,
        COLOR_EXTERIOR,
        SUCURSAL_ID,
        ESTADO_ID,
        KILOMETRAJE,
        PRECIO,
        VIN 
        ) VALUES (
            V_PLACA,
            V_MARCA,
            V_MODELO,
            V_TRIM,
            V_COLOR_INTERIOR,
            V_COLOR_EXTERIOR,
            V_SUCURSAL,
            V_ESTADO,
             V_KILOMETRAJE,
             V_PRECIO,
              V_VIN
        );
END;


CREATE OR REPLACE PROCEDURE sp_update_carro (
    V_ID NUMBER,
    V_PLACA VARCHAR2,
    V_MARCA NUMBER,
    V_MODELO NUMBER,
    V_TRIM NUMBER,
    V_COLOR_INTERIOR NUMBER,
    V_COLOR_EXTERIOR NUMBER,
    V_SUCURSAL NUMBER,
    V_ESTADO NUMBER,
    V_KILOMETRAJE NUMBER,
    V_PRECIO	NUMBER,
    V_VIN VARCHAR2
) AS
BEGIN 
    UPDATE T_CARRO SET
        PLACA = V_PLACA,
        MARCA_ID = V_MARCA,
        MODELO_ID = V_MODELO,
        TRIM_ID = V_TRIM,
        COLOR_INTERIOR=V_COLOR_INTERIOR,
        COLOR_EXTERIOR=V_COLOR_EXTERIOR,
        SUCURSAL_ID=V_SUCURSAL,
        ESTADO_ID=V_ESTADO,
        KILOMETRAJE = V_KILOMETRAJE,
        PRECIO = V_PRECIO,
        VIN= V_VIN
        
    WHERE
        CARRO_ID = V_ID;
        
END;
/

CALL SP_UPDATE_CARRO(1,'4568',1,1,3,1,2,1,1,53400,5000000,'DF138');


CREATE OR REPLACE PROCEDURE sp_delete_carro (
    V_ID NUMBER
) AS
BEGIN 
    DELETE FROM T_CARRO
    WHERE
        carro_id = V_ID;
        
END;

CALL SP_DELETE_CARRO(1);


INSERT INTO T_DISTRITO(distrito)values('Tejar');
INSERT INTO T_DISTRITO(distrito)values('San Antonio');
INSERT INTO T_DISTRITO(distrito)values('Monterrey');

INSERT INTO T_CANTON(canton)values('El Guarco');
INSERT INTO T_CANTON(canton)values('Alajuelita');
INSERT INTO T_CANTON(canton)values('Aserri');

INSERT INTO T_PROVINCIA(provincia)values('Cartago');
INSERT INTO T_PROVINCIA(provincia)values('San Jose');
INSERT INTO T_PROVINCIA(provincia)values('Heredia');

INSERT INTO T_DIRECCION(PROVINCIA_ID,CANTON_ID,DISTRITO_ID,DETALLES,UBICACION)VALUES
(1,1,1,'muro amarillo','Plaza de tejar');
INSERT INTO T_DIRECCION(PROVINCIA_ID,CANTON_ID,DISTRITO_ID,DETALLES,UBICACION)VALUES
(2,2,2,'mano derecha 100 metros sur de la iglesia de San Antonio','calle 12 San Antonio');
INSERT INTO T_DIRECCION(PROVINCIA_ID,CANTON_ID,DISTRITO_ID,DETALLES,UBICACION)VALUES
(2,3,3,'mano izquierda 50 metros norte de la avenida 12 de Monterrey','calle 12 San Antonio');


INSERT INTO T_SUCURSAL(NUMERO,NOMBRE,TELEFONO,DIRECCION_ID)VALUES(123,'Felipe','888-888',1);
INSERT INTO T_SUCURSAL(NUMERO,NOMBRE,TELEFONO,DIRECCION_ID)VALUES(675,'Carlos','999-999',2);
INSERT INTO T_SUCURSAL(NUMERO,NOMBRE,TELEFONO,DIRECCION_ID)VALUES(456,'Julian','444-444',3);


INSERT INTO T_MOTOR(CILINDRAJE,MARCA_ID)VALUES('1600',1);
INSERT INTO T_MOTOR(CILINDRAJE,MARCA_ID)VALUES('3000',2);
INSERT INTO T_MOTOR(CILINDRAJE,MARCA_ID)VALUES('1500',3);

INSERT INTO T_TRANSMISION(TRANSMISION)VALUES('Manual');
INSERT INTO T_TRANSMISION(TRANSMISION)VALUES('Automatico');

INSERT INTO T_TRIM(CODIGO,MOTOR_ID,TRANSMISION_ID,NUMERO_PUERTAS)VALUES('K23',1,1,4);
INSERT INTO T_TRIM(CODIGO,MOTOR_ID,TRANSMISION_ID,NUMERO_PUERTAS)VALUES('F78',2,2,4);
INSERT INTO T_TRIM(CODIGO,MOTOR_ID,TRANSMISION_ID,NUMERO_PUERTAS)VALUES('J90',3,2,4);

INSERT INTO T_ESTADO(ESTADO)VALUES('Nuevo');
INSERT INTO T_ESTADO(ESTADO)VALUES('Usado');
INSERT INTO T_ESTADO(ESTADO)VALUES('Oculto');

INSERT INTO T_MARCA(MARCA)VALUES('Nissan');
INSERT INTO T_MARCA(MARCA)VALUES('Toyota');
INSERT INTO T_MARCA(MARCA)VALUES('Suzuki');

INSERT INTO T_MODELO(MODELO)VALUES('Kicks');
INSERT INTO T_MODELO(MODELO)VALUES('Fortuner SRV');
INSERT INTO T_MODELO(MODELO)VALUES('XL7');

INSERT INTO T_COLOR(COLOR)VALUES('Blanco');
INSERT INTO T_COLOR(COLOR)VALUES('Negro');
INSERT INTO T_COLOR(COLOR)VALUES('Beige');
INSERT INTO T_COLOR(COLOR)VALUES('Morado');
INSERT INTO T_COLOR(COLOR)VALUES('Rojo');
INSERT INTO T_COLOR(COLOR)VALUES('Azul');

INSERT INTO T_CARRO(placa,marca_id,modelo_id,trim_id,color_interior,
color_exterior,sucursal_id,estado_id,kilometraje,precio,vin)values('GF54',1,1,1,1,2,1,1,53890,9000000,'DF129');
INSERT INTO T_CARRO(placa,marca_id,modelo_id,trim_id,color_interior,
color_exterior,sucursal_id,estado_id,kilometraje,precio,vin)values('KI12',2,2,2,3,6,2,1,37322,11000000,'345JH');
INSERT INTO T_CARRO(placa,marca_id,modelo_id,trim_id,color_interior,
color_exterior,sucursal_id,estado_id,kilometraje,precio,vin)values('ER74',3,3,3,2,1,3,2,47415,8000000,'DF129');