BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BANCO CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CARRO CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COTIZACION CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ESTADO_VEHICULO CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MARCA CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PROVINCIA CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;